syntax = "proto3";

option java_package = "com.gmail.comosense.calculator.data.proto";
option java_multiple_files = true;

message HistoryStore {
  repeated Calculation calculations = 1;
}

message Calculation {
  repeated Symbol expression = 1;
  repeated Symbol result = 2;
}

message Symbol {
  oneof value {
    bool positive = 1;
    bool negative = 2;

    int32 digit = 3;
    bool point = 4;

    bool open_parenthesis = 9;
    bool close_parenthesis = 10;

    bool add = 11;
    bool subtract = 12;
    bool multiply = 13;
    bool divide = 14;
  }
}
